version: '3.9'
services:
  typoteka.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: typoteka.account.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: typoteka-account

    ports:
      - 27017:27017

    volumes:
      - typoteka.mongo.account:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-account --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  typeoteka.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: typeoteka.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@typoteka.account.mongo:27017/

volumes:
  typoteka.mongo.account:
